language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

cache:
  directories:
    - vendor

before_script:
  - composer install -o

script:
  - ./vendor/bin/parallel-lint -e php --exclude vendor .  # Lint all files first.
  - ./phpdoccheck --exclude=vendor --fail-on-warnings     # Check docblocks.
