#!/usr/bin/env php
<?php
/**
 * PHP Docblock Checker
 *
 * @copyright    Copyright 2014, Block 8 Limited.
 * @license      https://github.com/Block8/php-docblock-checker/blob/master/LICENSE.md
 * @link         http://www.phptesting.org/
 */

$ownVendorAutoloader = dirname(__FILE__) . '/vendor/autoload.php';
$parentVendorAutoloader = dirname(__FILE__) . '/../../autoload.php';

if (file_exists($ownVendorAutoloader)) {
    require_once($ownVendorAutoloader);
} elseif (file_exists($parentVendorAutoloader)) {
    require_once($parentVendorAutoloader);
}

require_once(dirname(__FILE__) . '/PhpDocblockChecker/CheckerApplication.php');
require_once(dirname(__FILE__) . '/PhpDocblockChecker/CheckerCommand.php');

$command = new PhpDocblockChecker\CheckerCommand();

$application = new PhpDocBlockChecker\CheckerApplication();
$application->add($command);
$application->run();
